spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/st?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: qwe123
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait:
        max-idle: 0
    timeout: 10000s

server:
  port: 8088

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.lss.st.model

logging:
  level:
    root: info
